
# values provided here will override default values
# any default parameter can be overriden
# but only the ones listed here should be overridden
# 
etcd_dirlist:
  - tag: ssd  # some meaningful name for the test/config
    dir: /tmp # /mnt/ssdmnt/etcd
  - tag: hdd
    dir: /tmp # /mnt/hddmnt/etcd

seqw_dir: /tmp # /mnt/hddnt/other
randrw_dir: /tmp # /mnt/hddmnt/other
# output_dir: "."

# target data set size >= 2x cache size (i.e. total memory)
# recommended: power of 2, multiple of highest value in numjobs_list
# make sure there is enough space on the devices
#
seqw_dataset_sz_gb: 4 
randrw_dataset_sz_gb: 4 

# get latency for different load points
# more numjobs usualy means higher load
#
numjobs_list:
  - 2
  - 4

# common parameter for all workloads
#
# runtime_sec: 180

