
# etcd_dirlist: these should be on devices used by etcd
# this allows testing latency of different etcd configurations
# seqw_dir and randrw_dir should be on devices used by other workloads
# typically, seqw_dir and randrw_dir are the same
#
etcd_dirlist:
  - tag: ssd
    dir: /tmp # /mnt/ssdmnt/raft
  - tag: hdd
    dir: /tmp # /mnt/hddmnt/raft

seqw_dir: /tmp # /mnt/hddnt/other
randrw_dir: /tmp # /mnt/hddmnt/other
output_dir: /tmp

# target data set size >= 2x cache size (i.e. total memory)
# power of 2 recommended
# make sure there is enough space on the devices
#
seqw_dataset_sz_gb: 4 # 64
randrw_dataset_sz_gb: 4 # 128

# get latency for different load points
# more numjobs usualy means higher load
#
numjobs_list:
  - 2
  - 4

# common parameter for all workloads
#
# runtime_sec: 180

